<?php

namespace proyecto1\SeminarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeminarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeminarioRepository extends EntityRepository
{
    public function findEventosAnteriores($seminario)
    {
        $fechaHoy= new \DateTime('today');
        $em = $this->getEntityManager();
        $dql = 'SELECT e FROM SeminarioBundle:Evento e WHERE e.seminario = :seminario AND e.fecha < :fecha ORDER BY e.fechaCap DESC';
        $consulta = $em->createQuery($dql);
        $consulta->setParameters(array('fecha'=>$fechaHoy ,'seminario'=>$seminario));
        return $consulta->getResult();
    }
    public function findEventosSemana()
    {
        $fecha= date("W");
        $lunes= date('Y/m/d',strtotime(date("Y")."W".$fecha."1"));
        $viernes= date('Y/m/d',strtotime(date("Y")."W".$fecha."5"));
        $em = $this->getEntityManager();
        $dql = 'SELECT e FROM SeminarioBundle:Evento e WHERE e.fecha BETWEEN :lunes AND :viernes ORDER BY e.fechaCap DESC';
        $consulta = $em->createQuery($dql);
        //$consulta->setParameter('fecha',$fechaHoy);
        //$consulta-> setParameter('seminario',$seminario);
        $consulta->setParameters(array('lunes'=>$lunes,'viernes'=>$viernes));
        return $consulta->getResult();
    }
    public function findEventosSemanaSig()
    {
        $fecha= date("W")+1;
        $lunes= date('Y/m/d',strtotime(date("Y")."W".$fecha."1"));
        $viernes= date('Y/m/d',strtotime(date("Y")."W".$fecha."5"));
        $em = $this->getEntityManager();
        $dql = 'SELECT e FROM SeminarioBundle:Evento e WHERE e.fecha BETWEEN :lunes AND :viernes ORDER BY e.fechaCap DESC';
        $consulta = $em->createQuery($dql);
        //$consulta->setParameter('fecha',$fechaHoy);
        //$consulta-> setParameter('seminario',$seminario);
        $consulta->setParameters(array('lunes'=>$lunes,'viernes'=>$viernes));
        return $consulta->getResult();
    }
}

