security:
    encoders:

        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

#    role_hierarchy:
#        ROLE_USUARIO:   ROLE_USER
#        ROLE_ADMIN:      ROLE_USUARIO


    providers:
        in_memory:
            memory:
                users:
                    miguel:  { password: $2a$04$QpBMKODUP6k.ylQhBuSxFu8XnzaklIN6LFLZOWYBk.hL3hm9n4eJe, roles: [ 'ROLE_USUARIO' ] }
                    admin: { password: $2a$04$NPoZMW1/0F.s7Ugx6.MgveeDNp/ksGRIkUuVLLVb3MhoK59ZaIQBi, roles: [ 'ROLE_ADMIN' ] }


    firewalls:
        secured_area:
            pattern:    ^/ #cualquier peticion entrante
            anonymous: ~ #acceso usuarios anonimos
            http_basic: ~
            #stateless:  false
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /seminario
            logout:

                path: /logout
                target: /seminario
                delete_cookies:
                   a: { path: null, domain: null }
                   b: { path: null, domain: null }
                   # admin: { path: /evento, domain: null }


    access_control:

       - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/evento, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/seminario, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/responsable, roles: ROLE_ADMIN }





